#NAME: Aashita Patwari, Divij Ohri
#EMAIL: harshupatwari@gmail.com, divijohri28@gmail.com

build: lab3b.py
	rm -rf lab3b
	ln -s lab3b.py lab3b
	chmod +x lab3b

clean:
	rm -f lab3b *.tar.gz

dist: 
	tar -cvzf lab3b-004810708.tar.gz lab3b.py Makefile README