# NAME: Divij Ohri, Aashita Patwari
# EMAIL: divijohri28@gmail.com, harshupatwari@gmail.com
# ID: 404821856, 004810708

build: lab3a.c
	gcc -g -Wall -Wextra -std=gnu99 lab3a.c -o lab3a

clean:
	rm -f lab3a *.txt *.tar.gz *.o *~
	
dist: 
	tar -cvzf lab3a-004810708.tar.gz README Makefile lab3a.c ext2_fs.h